'''Add to the module coin.py, a function called summary(), 
which shows on the screen some information generated by 
the functions that we already have in the module created so far.'''

import coin

p = float(input('Type the price: $'))

coin.summary(p,80,35)